import { cookies } from 'next/headers'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const cookieStore = await cookies()
    const theme = cookieStore.get('theme')?.value ?? 'light'
    return (
        <html lang="ja" className={theme === 'dark' ? 'dark' : 'light'}>
            <body>{children}</body>
        </html>

    )
}
