import './globals.css'
import type { Metadata } from 'next' 

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body className="font-sans text-gray-800 bg-gray-50">{children}</body>
    </html>
  )
}
